### ISSUE TITLE
mac 提示不支持‘repetition_penalty‘参数

### ISSUE THREAD

**Issue by hhrensheng** [li-plus/chatglm.cpp#104]
本人 macbook m1 pro 16G
chatglm2-6b模型，使用mac加速，本地运行报错提示不支持repetition_penalty参数

`python3 chatglm_cpp/convert.py -i THUDM/chatglm2-6b -t q4_0 -o chatglm-ggml2.bin`
`cmake -B build -DGGML_METAL=ON && cmake --build build -j`
以cli模式运行
`python3 ./examples/cli_chat.py -m chatglm-ggml2.bin -i`
报以下错误
<img width="882" alt="image" src="https://github.com/li-plus/chatglm.cpp/assets/29398035/0a806483-f66e-4822-9986-4221ca3b2bc7">
请问是为什么呢

**Comment by hhrensheng** [comment]
发现安装的chatglm-cpp版本是0.2.4,是因为版本没更新吗

**Comment by li-plus** [comment]
刚发布了 0.2.5，可以装最新的 `chatglm-cpp` 试试，应该支持上这个参数了
