### ISSUE TITLE
更新8月23日GGML后报错

### ISSUE THREAD

**Issue by lwo2002** [li-plus/chatglm.cpp#108]
系统：mac
版本：8月23日
报错信息：调用api后，返回错误：GGML_ASSERT: /private/var/folders/h6/jks7f7f13ss8x5p2ynl183740000gn/T/pip-install-hnq21nov/chatglm-cpp_74c5f294237a4359a25cca393ae04305/third_party/ggml/src/ggml-metal.m:906: false && "not implemented"
zsh: abort      python examples/api_demo.py
请各位大神指导，谢谢。

**Comment by li-plus** [comment]
Metal 只支持 q4_0, q4_1, f16 类型的 GGML 模型，你的模型是什么类型的呢

**Comment by lwo2002** [comment]
谢谢大佬，我尝试了Q8，我调整回来，great Project

**Comment by lwo2002** [comment]
谢谢大佬，我尝试了Q8，我调整回来，great Project
