### ISSUE TITLE
cuBLAS error (CUDA error 222)

### ISSUE THREAD

**Issue by JianbangZ** [li-plus/chatglm.cpp#12]
built with cuBLAS, after that running ./main gives error
CUDA error 222 at xxxxxx/chatglm.cpp/third_party/ggml/src/ggml-cuda.cu:1835: the provided PTX was compiled with an unsupported toolchain.

**Comment by li-plus** [comment]
Your might need to upgrade your nvidia driver to match your cuda version. Please refer to https://forums.developer.nvidia.com/t/provided-ptx-was-compiled-with-an-unsupported-toolchain-error-using-cub/168292

**Comment by JianbangZ** [comment]
> Your might need to upgrade your nvidia driver to match your cuda version. Please refer to https://forums.developer.nvidia.com/t/provided-ptx-was-compiled-with-an-unsupported-toolchain-error-using-cub/168292

Yes upgrading driver solved the problem. I usually try to avoid upgrading nvidia drivers, as it always encounters some sort of problems. But I am glad it's resolved

**Comment by JianbangZ** [comment]
CLosed

**Comment by JianbangZ** [comment]
Resolved
