### ISSUE TITLE
Baichuan2 支持

### ISSUE THREAD

**Issue by raffeyang** [li-plus/chatglm.cpp#122]
百川发布2.0版本了，效果大幅提升。
[Baichuan2](https://github.com/baichuan-inc/Baichuan2)

**Comment by li-plus** [comment]
在 #123 支持了 Baichuan2-13B，它跟 Baichuan-13B 的结构完全一样，用现有的代码其实就能跑起来。

Baichuan2-7B 最近会支持下。

**Comment by unfish** [comment]
> 在 #123 支持了 Baichuan2-13B，它跟 Baichuan-13B 的结构完全一样，用现有的代码其实就能跑起来。
> 
> Baichuan2-7B 最近会支持下。

是不是只有chatglm2量化后能使用mps加速？baichuan2 13b转换后用mps方式编译运行会报错，只能用CPU。

**Comment by unfish** [comment]
报错信息：
/chatglm.cpp/third_party/ggml/src/ggml-metal.m:1046: false && "only power-of-two n_head implemented"

**Comment by zhangp365** [comment]
下载huggingface 百川1和2 的13b ggml模型，跑最新的0.26代码，总是报：CHATGLM_CHECK(magic == "ggml") << "model file is broken (bad magic)" ，是一定要自己转出模型吗？
百川1 13b地址：https://huggingface.co/xuqinyang/baichuan-13b-chat-ggml-int4/tree/main
百川2 13b 地址：https://huggingface.co/xuqinyang/Baichuan2-13B-Chat-ggml-Q5_1/tree/main
按道理应该可以直接使用转好的ggml模型的，麻烦看一下

**Comment by xwdreamer** [comment]
baichuan2-13b，在mac m2上跑速度特别慢。1分钟可能10 token都不到，这个正常吗

**Comment by zhangp365** [comment]
llama.cpp 已经直接支持baichuan2了，使用最新gguf格式直接可以跑。
