### ISSUE TITLE
你好，启动API的文件在哪，怎么启动api服务？
where is the api_demo.py?

### ISSUE THREAD

**Issue by Olbye** [li-plus/chatglm.cpp#126]

**Comment by nianhuiY** [comment]
可以参考这个issue：https://github.com/li-plus/chatglm.cpp/issues/91

**Comment by Olbye** [comment]
好了 非常感谢

**Comment by Olbye** [comment]
> 可以参考这个issue：https://github.com/li-plus/chatglm.cpp/issues/91

成功了 非常感谢
