### ISSUE TITLE
请问有计划支持GGUF格式吗？GGML已经被llama.cpp标记为deprecated了

### ISSUE THREAD

**Issue by valkryhx** [li-plus/chatglm.cpp#135]
如题。

**Comment by chenqiny** [comment]
支持

**Comment by li-plus** [comment]
chatglm.cpp ckpt 二进制协议与 llama.cpp 的 ggml 不完全相同的，已经具备表达不同模型结构的能力。目前尽量保持向后兼容，除非有特别需要否则尽量不改动。

**Comment by valkryhx** [comment]
收到！

**Comment by calvinweb** [comment]
> chatglm.cpp ckpt 二进制协议与 llama.cpp 的 ggml 不完全相同的，已经具备表达不同模型结构的能力。目前尽量保持向后兼容，除非有特别需要否则尽量不改动。

但是这样做的话 ctransfromers等其他ggml库就用不chatglm.cpp的制品

**Comment by JerryYao75** [comment]
目前chatglm有gguf的模型了吗？

**Comment by kkkkkk-a** [comment]
请问glm有没有gguf
