### ISSUE TITLE
Python Module 调用失败

### ISSUE THREAD

**Issue by suifei** [li-plus/chatglm.cpp#14]
# Macbook M1 pro 16G

## 编译成功

```shell
cmake -B build 成功
cmake --build build -j 成功
python convert.py -i ~/models/THUDM/chatglm2-6b -t f16 -o chatglm2-ggml-f16.bin 成功
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.28s/it]
Dumping model state: 100%|██████████████████████████████████████████████████████████████████████| 199/199 [00:35<00:00,  5.66it/s]
```
## 运行测试成功

```shell
./build/bin/main -m chatglm2-ggml-f16.bin -i
    ________          __  ________    __  ___
   / ____/ /_  ____ _/ /_/ ____/ /   /  |/  /_________  ____
  / /   / __ \/ __ `/ __/ / __/ /   / /|_/ // ___/ __ \/ __ \
 / /___/ / / / /_/ / /_/ /_/ / /___/ /  / // /__/ /_/ / /_/ /
 \____/_/ /_/\__,_/\__/\____/_____/_/  /_(_)___/ .___/ .___/
                                              /_/   /_/
Prompt   > 你好！
ChatGLM2 > 你好👋！我是人工智能助手 ChatGLM2-6B，很高兴见到你，欢迎问我任何问题。
```
成功速度很快

## Python Binding 有问题

```shell
pip install .
.....
Successfully built chatglm-cpp
Installing collected packages: chatglm-cpp
Successfully installed chatglm-cpp-0.2.0
```
运行 web_demo.py 失败

```shell
python web_demo.py -m chatglm2-ggml-f16.bin
Traceback (most recent call last):
  File "/Users/suifei/works/chatglm.cpp/web_demo.py", line 5, in <module>
    import chatglm_cpp
  File "/Users/suifei/works/chatglm.cpp/chatglm_cpp/__init__.py", line 5, in <module>
    import chatglm_cpp._C as _C
ModuleNotFoundError: No module named 'chatglm_cpp._C'
```
请问下这个是什么原因导致的，python module 调用失败

---

##  System environment

Apple M1 Pro 16 GB macOS(13.4.1 (22F82))

## The compilation was successful
```ruby
cmake -B build #Success
cmake --build build -j #Success
python convert.py -i ~/models/THUDM/chatglm2-6b -t f16 -o chatglm2-ggml-f16.bin #Success
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.28s/it]
Dumping model state: 100%|██████████████████████████████████████████████████████████████████████| 199/199 [00:35<00:00,  5.66it/s]
```

## The test was successful

```ruby
./build/bin/main -m chatglm2-ggml-f16.bin -i
    ________          __  ________    __  ___
   / ____/ /_  ____ _/ /_/ ____/ /   /  |/  /_________  ____
  / /   / __ \/ __ `/ __/ / __/ /   / /|_/ // ___/ __ \/ __ \
 / /___/ / / / /_/ / /_/ /_/ / /___/ /  / // /__/ /_/ / /_/ /
 \____/_/ /_/\__,_/\__/\____/_____/_/  /_(_)___/ .___/ .___/
                                              /_/   /_/
Prompt   > hello!
ChatGLM2 > Hello! How can I assist you today?
```
The success rate is fast.

## To install the Python binding from source, run:

```ruby
pip install .
.....
Successfully built chatglm-cpp
Installing collected packages: chatglm-cpp
Successfully installed chatglm-cpp-0.2.0
```

An error occurred while running web_demo.py.

```ruby
python web_demo.py -m chatglm2-ggml-f16.bin
Traceback (most recent call last):
  File "/Users/suifei/works/chatglm.cpp/web_demo.py", line 5, in <module>
    import chatglm_cpp
  File "/Users/suifei/works/chatglm.cpp/chatglm_cpp/__init__.py", line 5, in <module>
    import chatglm_cpp._C as _C
ModuleNotFoundError: No module named 'chatglm_cpp._C'
```

What is the reason for the failure of the Python module call?

**Comment by yuebo** [comment]
尝试把编译的出来so放到当前的chatglm_cpp目录下面
```bash
cp ./build/lib.linux-x86_64-cpython-310/chatglm_cpp/_C.cpython-310-x86_64-linux-gnu.so  ./chatglm_cpp/_C.cpython-310-x86_64-linux-gnu.so```

**Comment by suifei** [comment]
> 尝试把编译的出来so放到当前的chatglm_cpp目录下面
> 
> ```shell
> cp ./build/lib.linux-x86_64-cpython-310/chatglm_cpp/_C.cpython-310-x86_64-linux-gnu.so  ./chatglm_cpp/_C.cpython-310-x86_64-linux-gnu.so
> ```

问题已解决/The problem has been resolved.
```ruby
cd chatgml.cpp
cp ./build/lib.linux-x86_64-cpython-39/chatglm_cpp/_C.cpython-39-x86_64-linux-gnu.so ./chatglm_cpp/
```

**Comment by Gholls** [comment]
python setup.py build_ext --inplace

**Comment by xwdreamer** [comment]
> 

你好，我在mac上运行api方式启动，报错。
mac上并没有找到响应的so文件。
我把build目录下的全部内容都copy到chatglm_cpp下也没有用


<img width="346" alt="image" src="https://github.com/li-plus/chatglm.cpp/assets/1173919/1af9a0fd-08d8-4773-be8c-053b469457f1">


```
ModuleNotFoundError: No module named 'chatglm_cpp._C'
```

**Comment by peterlau0626** [comment]
其实把你的python脚本放到chatglm.cpp这个目录的外面执行就好了。

我观察到pip install .之后，在我自己的python目录下python3.8/site-packages是有chatglm_cpp目录的，证明其实已经安装成功了。
然后我在python3.8/site-packages这个目录执行python，输入import chatglm_cpp就不会报错了。但是在chatglm.cpp这个目录，我执行python，然后输入chatglm_cpp就报错了。所以也不知道为啥，反正在chatglm.cpp这个目录外面执行python就没问题了。

**Comment by Steven-Luo** [comment]
> > 
> 
> 你好，我在mac上运行api方式启动，报错。 mac上并没有找到响应的so文件。 我把build目录下的全部内容都copy到chatglm_cpp下也没有用
> 
> <img alt="image" width="346" src="https://private-user-images.githubusercontent.com/1173919/260200421-1af9a0fd-08d8-4773-be8c-053b469457f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzAwMzQsIm5iZiI6MTcwMjU2OTczNCwicGF0aCI6Ii8xMTczOTE5LzI2MDIwMDQyMS0xYWY5YTBmZC0wOGQ4LTQ3NzMtYmU4Yy0wNTNiNDY5NDU3ZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTYwMjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzJlODgzYjM4M2JlZGJmNjRmM2JmYmQ4MzI3MGUzNmQ1YjA1ZDBkYzVmYzM4NmE4ZDcxZGUzNThiMjNmYmNkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4WMAaS6svTMjS7i4WAiJZkvLxrqqeVA03MDJeuOgp38">
> ```
> ModuleNotFoundError: No module named 'chatglm_cpp._C'
> ```

上面有人回答了，不要在chatglm.cpp目录下运行，到其他目录，chatglm.cpp下也有个chatglm_cpp目录，在python里面import的时候会优先去这个目录下找，所以报找不到的错误了

**Comment by x4080** [comment]
Hi, after resolving the error
```
ModuleNotFoundError: No module named 'chatglm_cpp._C'
```

It still wont run :
```
ImportError: cannot import name 'computed_field' from 'pydantic' (/Users/edwardnone/miniconda3/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so)
```

Anybody successfully run this ? (m2 pro)

**Comment by yucl80** [comment]
将chatglm.cpp 下的chatglm_cpp 换个名称。
