### ISSUE TITLE
I want to know how your test data is generated.

### ISSUE THREAD

**Issue by weizhenhuan** [li-plus/chatglm.cpp#155]
I'm now working on a project using ggml. But test if my operator is written correctly is difficult. I want to your how your test data in tests/data directory is generated. Thanks for your nice work.

**Comment by li-plus** [comment]
The test data is manually generated using `test_convert.py` script. It creates a single-layer model, randomly initializes its params and inputs, runs forward in pytorch, and finally dumps all the weights and inputs into a binary file. You may need to change the model path to your own local path and make some small fix.

https://github.com/li-plus/chatglm.cpp/blob/f89f6fd01d9a2a659629622f8f25c9e53eee229e/tests/test_convert.py#L317-L384
