### ISSUE TITLE
support chatglm3 

### ISSUE THREAD

**Issue by quan2005** [li-plus/chatglm.cpp#157]
https:Huggingface.co/THUDM/chatglm3-6b-32k

The latest chatglm3-6b-32k has been released

Python3 chatglm_cpp/convert.py-I.. / chatglm3-6b-32k-t q4room1-o. /.. / chatglm3-6b-ggml-q4_1.bin

Conversion successful

MODEL=chatglm3-6b-ggml-q4_1.bin uvicorn chatglm_cpp.openai_api:app-host 127.0.0.1-port 8000

It also runs successfully.

But there are problems.
1. Reply unstable (there is no problem if you run it directly)
2. After the reply exceeds a certain content, the content cycle

--------------------

最新的chatglm3-6b-32k已经发布，

python3 chatglm_cpp/convert.py -i ../chatglm3-6b-32k -t q4_1 -o ../../chatglm3-6b-ggml-q4_1.bin

转换成功

MODEL=chatglm3-6b-ggml-q4_1.bin uvicorn chatglm_cpp.openai_api:app --host 127.0.0.1 --port 8000

运行也成功

但遇到问题
1. 回复不稳定（直接运行就没这个问题）
2. 回复超出一定内容后，内容循环

**Comment by li-plus** [comment]
ChatGLM3的tokenizer逻辑有更新，刚支持了，可以试试用最新的代码跑，看看还有没有不稳定的问题

**Comment by quan2005** [comment]
![image](https://github.com/li-plus/chatglm.cpp/assets/4606750/5a7e63a5-ad1d-4591-99e1-df46d5ae7b33)

在回答结束后，没能及时结束，会多出一些回答，如上图。

**Comment by li-plus** [comment]
试试用新代码重新执行 convert.py 转 chatglm3-6b，预期终端回显会以 `ChatGLM3 > ` 开头的

**Comment by quan2005** [comment]
![image](https://github.com/li-plus/chatglm.cpp/assets/4606750/98aaa7ae-12fb-406b-9d30-3ff0f38ebaf7)

我已经用了新代码重新执行 convert.py 转 chatglm3-6b，结果仍然没有符合预期进行输出。

我查看了你最近提交的代码，找到了问题。问题出在了我用的模型是chatglm3-6b-32k，这里的条件导向了chatglm2，我强制注释chatglm2的路径代码，convert后，终端成功回显会以 ChatGLM3 >  的开头。

**Comment by li-plus** [comment]
确实，感谢反馈~ 我要找一个新的 flag 来区分 chatglm2 和 chatglm3。

强制注释之后还会遇到输出不稳定的问题吗？

**Comment by quan2005** [comment]
尚没深入测试，简单用了一下，目测是正常

**Comment by gaoshine** [comment]
貌似tools支持不了，也是Tokenizer抛出异常：
File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.9/site-packages/chatglm_cpp/__init__.py", line 41, in chat
    input_ids = self.tokenizer.encode_history(history, max_context_length)
TypeError: encode_history(): incompatible function arguments. The following argument types are supported:
    1. (self: chatglm_cpp._C.BaseTokenizer, arg0: List[str], arg1: int) -> List[int]

Invoked with: <chatglm_cpp._C.ChatGLM3Tokenizer object at 0x10491cf70>, [{'role': 'system', 'content': 'Answer the following questions as best as you can. You have access to the following tools:', 'tools': [{'name': 'track', 'description': '追踪指定股票的实时价格', 'parameters': {'type': 'object', 'properties': {'symbol': {'description': '需要追踪的股票代码'}}, 'required': []}}]}, '你好'], 8192

**Comment by lilongxian** [comment]
我使用chaglm3-6b-32k模型，转换成chatglm-ggml.bin后，也cmake编译好了chatglm.cpp，运行/opt/cc/chatglm.cpp/build/bin$ ./main -m /opt/cc/chatglm-ggml.bin -i 报错：

Welcome to ChatGLM.cpp! Ask whatever you want. Type 'clear' to clear context. Type 'stop' to exit.

Prompt   > 你好
Floating point exception (core dumped)   

但是，我用llama.cpp编译后运行llama2-7b模型都正常，这会不会chatglm.cpp对gcc  g++版本号有要求？我这个是7.5的版本
@li-plus @quan2005 请求大佬帮助看一下问题在哪里，谢谢！

**Comment by hansjohn** [comment]
> 我使用chaglm3-6b-32k模型，转换成chatglm-ggml.bin后，也cmake编译好了chatglm.cpp，运行/opt/cc/chatglm.cpp/build/bin$ ./main -m /opt/cc/chatglm-ggml.bin -i 报错：
> 
> Welcome to ChatGLM.cpp! Ask whatever you want. Type 'clear' to clear context. Type 'stop' to exit.
> 
> Prompt > 你好 Floating point exception (core dumped)
> 
> 但是，我用llama.cpp编译后运行llama2-7b模型都正常，这会不会chatglm.cpp对gcc g++版本号有要求？我这个是7.5的版本 @li-plus @quan2005 请求大佬帮助看一下问题在哪里，谢谢！

我也遇到相同的问题，请问你解决了吗

**Comment by lilongxian** [comment]
解决了，就是gcc  g++的版本问题，建议使用11.4版本
