### ISSUE TITLE
Support ChatGLM3-6B System Prompt & Tool invocation

### ISSUE THREAD

**Issue by SolomonLeon** [li-plus/chatglm.cpp#169]
Tool invocation is a very useful feture in local inference. While it's currently only available for ChatGLM3-6B, the significance of implementing this feature remains very important.

Is the implementation of this feature already on the schedule? What can we do to help?

By the way, I can't system prompt parameter in the python binding, is there any way to config it?

**Comment by gaoshine** [comment]
同问，pipeline.chat 和 pipeline.generate 都不能再现 原模型 model.chat(tokenizer, query, history=history, role=role)中实现的 Tool功能。 请问量化后的chatglm3-ggml.bin是否能够支持 tools？

**Comment by gaoshine** [comment]
貌似作者的分支已经开始支持了，[new-prompt-fmt](https://github.com/li-plus/chatglm.cpp/tree/new-prompt-fmt)。我测试并没有成功，期待作者放出例子，感觉chatglm3的这次prompt的改动有些大，一些token的id大于60000的应该都是保留的token，防止用户注入。

**Comment by gaoshine** [comment]
貌似作者的分支已经开始支持了，[new-prompt-fmt](https://github.com/li-plus/chatglm.cpp/tree/new-prompt-fmt)。我测试并没有成功，期待作者放出例子，感觉chatglm3的这次prompt的改动有些大，一些token的id大于60000的应该都是保留的token，防止用户注入。

**Comment by li-plus** [comment]
System prompt & function call & code interpreter have been supported in #197. Just pull the code, install the latest `chatglm-cpp` and try out `chatglm3_demo.py`.
