### ISSUE TITLE
Windows下Python Binding安装问题

### ISSUE THREAD

**Issue by M1saka10010** [li-plus/chatglm.cpp#177]
在没有开启cuda之前是正常的，本地编译含cuda加速也是正常的。但是python那边只要一开启cuda安装，使用的时候就会报错

```
Traceback (most recent call last):
  File "D:\chatglm.cpp\examples\web_demo.py", line 6, in <module>
    import chatglm_cpp
  File "C:\ProgramData\miniconda3\envs\chatglm_cpp\lib\site-packages\chatglm_cpp\__init__.py", line 6, in <module>
    import chatglm_cpp._C as _C
ImportError: DLL load failed while importing _C: 找不到指定的模块。
```

安装环境的命令如下：

```
call activate.bat chatglm_cpp
set "TRACKFILEACCESS=false"
set "CMAKE_ARGS=-DGGML_CUBLAS=ON"
pip install chatglm-cpp --force-reinstall -v --no-cache
```

**Comment by M1saka10010** [comment]
补充：
目录`C:\ProgramData\miniconda3\envs\chatglm_cpp\lib\site-packages\chatglm_cpp\`下有文件
_C.cp310-win_amd64.pyd

**Comment by M1saka10010** [comment]
尝试了
https://github.com/li-plus/chatglm.cpp/issues/91
https://github.com/li-plus/chatglm.cpp/issues/14
都无果

**Comment by Jzhnakui** [comment]
> 尝试了 #91 #14 都无果

请问解决了吗？我是windows，一样的报错
G:\fuckkk\chatglm.cpp\build\lib.win-amd64-cpython-310\chatglm_cpp
![image](https://github.com/li-plus/chatglm.cpp/assets/49728819/2fc1214f-2c1e-46d6-944a-898c19f0cdbb)
D:\Anaconda3-2021.11\envs\chatglm\Lib\site-packages\chatglm_cpp
![image](https://github.com/li-plus/chatglm.cpp/assets/49728819/105dc8fa-697e-4ad6-9075-1133f2f55cdd)

也不再冲突目录中加载；
![image](https://github.com/li-plus/chatglm.cpp/assets/49728819/be96f44b-0b6d-4965-9ad5-0f2ba38556e8)

**Comment by M1saka10010** [comment]
> > 尝试了 #91 #14 都无果
> 
> 请问解决了吗？我是windows，一样的报错 G:\fuckkk\chatglm.cpp\build\lib.win-amd64-cpython-310\chatglm_cpp ![image](https://user-images.githubusercontent.com/49728819/281506967-2fc1214f-2c1e-46d6-944a-898c19f0cdbb.png) D:\Anaconda3-2021.11\envs\chatglm\Lib\site-packages\chatglm_cpp ![image](https://user-images.githubusercontent.com/49728819/281507011-105dc8fa-697e-4ad6-9075-1133f2f55cdd.png)
> 
> 也不再冲突目录中加载； ![image](https://user-images.githubusercontent.com/49728819/281507234-be96f44b-0b6d-4965-9ad5-0f2ba38556e8.png)

没有解决，搞了五六个小时之后我放弃抵抗了

**Comment by EpicLolia** [comment]
我在#181提供了一个解决方案，你可以试一下

**Comment by M1saka10010** [comment]
> 我在 #181 提供了一个解决方案，你可以试一下

感谢，已解决
