### ISSUE TITLE
如何控制API服务的线程数量

### ISSUE THREAD

**Issue by charSLee013** [li-plus/chatglm.cpp#180]
# 问题描述
我尝试使用 `num_threads=16 uvicorn chatglm_cpp.openai_api:app --host 127.0.0.1 --port 8000` 启动 OpenAI 服务
并通过设置环境变量来控制线程数量，但无论我如何设置环境变量 num_threads，线程数量似乎都没有变化。

我注意到 [openai_api.py](https://github.com/li-plus/chatglm.cpp/blob/95d3b8c1730d646c1916701eaf4ce03fe98baa8c/chatglm_cpp/openai_api.py#L18) 是有设置到获取 `num_threads`的环境变量的

我该如何正确设置线程数或者有其他解决方法？

**Comment by StrayDragon** [comment]
```
NUM_THREADS=16 uvicorn chatglm_cpp.openai_api:app --host 127.0.0.1 --port 8000
```

得用大写才行 https://docs.pydantic.dev/1.10/usage/settings/#parsing-environment-variable-values
