### ISSUE TITLE
p-tuning后的chatglm3模型，经量化后怎么把微调的知识全忘了？

### ISSUE THREAD

**Issue by chris-rong** [li-plus/chatglm.cpp#189]
merge_model1/文件夹下有：
![image](https://github.com/li-plus/chatglm.cpp/assets/85501211/cbc6a32c-e6c6-467c-9541-3e91e85cb38c)
pytorch_model.bin大小为12G，是ptuning后的模型合并到原模型中的结果，然后执行
```
python3 chatglm_cpp/convert.py -i merge_model1/ -t q4_1 -o merge_model1/chatglm-ggml-q4_1.bin
```
后得到chatglm-ggml-q4_1.bin，大小为3.7G,但是量化后的模型已经把微调的知识全忘了，回答结果跟原模型一模一样。请问这个convert.py是会去找源模型而不是我自己微调后的模型吗？（为避免是合并后的模型就没有微调的知识，自己验证过了，pytorch_model.bin回答的是微调后的结果，但是量化后就全消失了）

**Comment by lzw12138** [comment]
同问，我用lora也是

**Comment by li-plus** [comment]
目前还不支持转换 p-tuning 的模型，会考虑支持下。

lora 是支持的，需要加 `-l` 参数指定 lora checkpoint，参考 README：
> For LoRA model, add -l <lora_model_name_or_path> flag to merge your LoRA weights into the base model.

**Comment by chris-rong** [comment]
> 目前还不支持转换 p-tuning 的模型，会考虑支持下。
> 
> lora 是支持的，需要加 `-l` 参数指定 lora checkpoint，参考 README：
> 
> > For LoRA model, add -l <lora_model_name_or_path> flag to merge your LoRA weights into the base model.

我已经将p-tuning微调的参数合并到原模型中了，然后再对合并的模型量化，这样也不行吗？

**Comment by lzw12138** [comment]
> 目前还不支持转换 p-tuning 的模型，会考虑支持下。
> 
> lora 是支持的，需要加 `-l` 参数指定 lora checkpoint，参考 README：
> 
> > For LoRA model, add -l <lora_model_name_or_path> flag to merge your LoRA weights into the base model.

我看了一下export的源码 ，发现-l貌似不起作用耶，在convert那个函数里

**Comment by TX-Yeager** [comment]
> 目前还不支持转换 p-tuning 的模型，会考虑支持下。
> 
> lora 是支持的，需要加 `-l` 参数指定 lora checkpoint，参考 README：
> 
> > For LoRA model, add -l <lora_model_name_or_path> flag to merge your LoRA weights into the base model.

ptuning后的模型，大概啥时候可以支持？或者有解决思路吗？
