### ISSUE TITLE
chatGLM2 & llama.cpp

### ISSUE THREAD

**Issue by JianbangZ** [li-plus/chatglm.cpp#2]
请问这个REPO可以直接支持chatGLM2吗？
另外最近2周llama.cpp里很多关于cublas的优化提速代码是否已经merge进来了？

**Comment by li-plus** [comment]
ChatGLM2正在开发哈，预计本周发布，llama.cpp的优化到时也会merge进来

**Comment by nezhazheng** [comment]
@li-plus 借楼问下，有langchain的支持吗，https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp，这个模块是否能支持咱们chatglm.cpp

**Comment by aonoa** [comment]
切换到chatglm2分支，好像已经可以用了

**Comment by JianbangZ** [comment]
> 切换到chatglm2分支，好像已经可以用了

我这边报AttributeError: 'ChatGLMConfig' object has no attribute 'position_encoding_2d'

**Comment by aonoa** [comment]
> 

你的操作步骤是什么呢

**Comment by aonoa** [comment]
![image](https://github.com/li-plus/chatglm.cpp/assets/32682251/7b03e812-5eb1-4d09-8374-8047bd6bc79c)

这个是我用的ChatGLM2-6B 4-bit的效果，除了有点慢，别的没啥问题

**Comment by JianbangZ** [comment]
> 你的操作步骤是什么呢

我用convert.py 到q4_0的时候报错

**Comment by li-plus** [comment]
> > 切换到chatglm2分支，好像已经可以用了
> 
> 我这边报AttributeError: 'ChatGLMConfig' object has no attribute 'position_encoding_2d'

ChatGLM2 已经支持了，可以参考 main 分支最新的 README 试试

**Comment by JianbangZ** [comment]
> > > 切换到chatglm2分支，好像已经可以用了
> > 
> > 
> > 我这边报AttributeError: 'ChatGLMConfig' object has no attribute 'position_encoding_2d'
> 
> ChatGLM2 已经支持了，可以参考 main 分支最新的 README 试试

太棒了。另外想问下为什么不支持k-quant呢？

**Comment by li-plus** [comment]
k-quant 在开发中，因为不想像 llama.cpp 那样多一步 quantize，需要在 python 里开发并对齐 ggml c++ 实现。
