### ISSUE TITLE
Baichuan2-7b-chat Tokenizer and outputs difference between your repo and officical hugginface example.

### ISSUE THREAD

**Issue by Zhenzhong1** [li-plus/chatglm.cpp#208]
Hi, I found some differneces between your baichuan2-7b-chat example and [hugginface baichuan2-7b-chat example](https://huggingface.co/baichuan-inc/Baichuan-7B).

About tokenizer.
```
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/Baichuan2-7B-chat", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("baichuan-inc/Baichuan2-7B-chat", device_map="auto", trust_remote_code=True)
inputs = tokenizer('你好吗', return_tensors='pt')
print(inputs)

# {'input_ids': tensor([[16829, 93122]]), 'attention_mask': tensor([[1, 1]])}
```
I found there were no specical tokens 195 and 196 from the transformers tokenizer, but you repo adds these two special tokens for each sencetence. I don't know why adding these two speical tokens and how do you know this two special tokens? Coule you please help this?~

About outputs:
```
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/Baichuan2-7B-chat", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("baichuan-inc/Baichuan2-7B-chat", device_map="auto", trust_remote_code=True)
inputs = tokenizer('你好吗', return_tensors='pt')
pred = model.generate(**inputs, max_new_tokens=64,repetition_penalty=1.1)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```
output screenshot:
![image](https://github.com/li-plus/chatglm.cpp/assets/109137058/c27e7496-7674-4ce5-93de-6f5f1394496c)

As the screenshot shown, not sure why it's different from your example, but outputs of your repo looks good!
![image](https://github.com/li-plus/chatglm.cpp/assets/109137058/51bd4405-4311-4f53-9891-0d32226eff62)

**Comment by li-plus** [comment]
There are actually two kinds of tokenization strategies. For base models (pretrained without SFT) like [Baichuan2-7B](https://huggingface.co/baichuan-inc/Baichuan-7B), it's fine to directly encodes the text into token ids without adding any special prefix or suffix tokens, just as your `tokenizer('你好吗', return_tensors='pt')`. However, for chat models (after SFT) like [Baichuan2-7B-Chat](https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat), they are usually trained on a specific prompt template during SFT. When they're deployed for inference, their prompt patterns should be respected. In this case, Baichuan2-7B-Chat uses a prompt template like: (see https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/main/generation_utils.py#L30-L43)
```
<user_token_id>prompt1<assistant_token_id>response1<user_token_id>prompt2<assistant_token_id>response2 ...
```
where `<user_token_id>` is 195 and `<assistant_token_id>` is 196 according to their generation config (see https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/main/generation_config.json#L5-L6). We should add these special tokens to make it chat normally.

**Comment by Zhenzhong1** [comment]
Thanks for your reply. I closed this issue.
