### ISSUE TITLE
Cmake error on Windows

### ISSUE THREAD

**Issue by I-hsin-Chen** [li-plus/chatglm.cpp#217]
After running `cmake -B build` , I got the error as below : 

```
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

I have tried setting  CMAKE_CXX_COMPILER to my g++ by `set CMAKE_ARGS="-DCMAKE_CXX_COMPILER=C:\msys64\ucrt64\bin\g++` but it doesn't work though. Hope to get some suggestions." Thank you !

**Comment by I-hsin-Chen** [comment]
Solved with MingGW

**Comment by kingpingyue** [comment]
请问解决了吗  我也是这个问题 Windows下该怎么编译chatglm.cpp

**Comment by niweixiaoshihaomeilll** [comment]
请问有具体得解决方案嘛

**Comment by sjtuzhaoxh** [comment]
PS D:\Projects\model\chatglm.cpp> cmake -B build
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory


-- Configuring incomplete, errors occurred!
