### ISSUE TITLE
为什么4090显卡用不了，编译成功之后也是用的cpu推理

### ISSUE THREAD

**Issue by sammichenVV** [li-plus/chatglm.cpp#235]
```
cmake -B build -DCMAKE_CUDA_COMPILER="/home/xx/anaconda3/bin/nvcc" -DGGML_CUBLAS=ON -DCUDA_ARCHITECTURES="89"
cmake --build build -j 
```
用这个命令编译之后运行模型还是cpu推理的
`./build/bin/main -m chatglm2-ggml.bin -p 你好 --top_p 0.8 --temp 0.8
`

**Comment by gaojuntian** [comment]
请问解决了吗

**Comment by sammichenVV** [comment]
> 请问解决了吗

没有，你也有遇到么，现在是用不来哦GPU

**Comment by gaojuntian** [comment]
嗯嗯，一样

**Comment by sammichenVV** [comment]
> 嗯嗯，一样

用这个命令试试 cmake -B build -DGGML_CUBLAS=ON -DCUDA_ARCHITECTURES="89" &&  cmake --build build -j --config Release 如果报错，指定下nvcc的位置

**Comment by TGJek** [comment]
额，看起来是你忘记在构建ML库的时候，给ML库的构建选项加上"使用CUBLAS"了？
