### ISSUE TITLE
chatglm4: Run ./build/bin/main,  Error:   invalid model type 4

### ISSUE THREAD

**Issue by guissy** [li-plus/chatglm.cpp#307]
./build/bin/main -m chatglm4-ggml.bin -p "你好"

报错
/chatglm.cpp:1435 invalid model type 4

**Comment by li-plus** [comment]
试试先 pull 一下最新代码，重新编译，再加载模型呢
```
git pull origin main
git submodule update --init --recursive
cmake -B build
cmake --build build -j --config Release
```

**Comment by guissy** [comment]
> 试试先 pull 一下最新代码，重新编译，再加载模型呢
> 
> ```
> git pull origin main
> git submodule update --init --recursive
> cmake -B build
> cmake --build build -j --config Release
> ```

It works! thank you!!
