### ISSUE TITLE
libre2.so.11 not found

### ISSUE THREAD

**Issue by hooploop** [li-plus/chatglm.cpp#316]
使用docker构建了支持cuda的镜像，运行时出现如下信息
./build/bin/main: error while loading shared libraries: libre2.so.11: cannot open shared object file: No such file or directory

ldd展示如下
![image](https://github.com/li-plus/chatglm.cpp/assets/97428008/b108e05c-6a1f-459f-8a64-d790d7885c02)

docker构建命令如下
docker build . --network=host -t chatglm.cpp-cuda \
    --build-arg BASE_IMAGE=nvidia/cuda:12.2.2-devel-ubuntu22.04 \
    --build-arg CMAKE_ARGS="-DGGML_CUBLAS=ON -DCUDA_ARCHITECTURES=75"

构建之前做了如下两个操作
1.构建时替换了基础镜像的版本，示例中是nvidia/cuda:12.2.0-devel-ubuntu20.04
2.third_part中关联的代码的zip包为手动下载

**Comment by li-plus** [comment]
可以 pull 下最新代码，改成静态链接了，不用 copy .so 过去
