### ISSUE TITLE
我觉得lora option没有merge lora/qlora

### ISSUE THREAD

**Issue by YerongLi** [li-plus/chatglm.cpp#32]
`-l <lora_model_name_or_path>`

model 的behaviour不一样

**Comment by YerongLi** [comment]
My mistake.

**Comment by cherishtttz** [comment]
> `-l <lora_model_name_or_path>`
> 
> model 的behaviour不一样

hello 请问转换lora模型成功了吗？我加了这句貌似没有作用，推理速度和glm2原模型一样。

**Comment by wanshichenguang** [comment]
起作用了，但是没有完全起
