### ISSUE TITLE
Python脚本 加载转化模型非常慢

### ISSUE THREAD

**Issue by qiuwenbo1** [li-plus/chatglm.cpp#334]
操作系统：ubuntu22.04
架构：x64
gpu：3090
加载方式：写python脚本加载
模型：chatglm2

问题：执行脚本后，加载模型需要很久，有时候又非常快。快的时候瞬间可以，慢的时候半小时都不行。下图是加载的截图，一直卡在这里
![image](https://github.com/user-attachments/assets/a8bae389-f6ae-4eba-b128-6dbbb7dfa146)

**Comment by li-plus** [comment]
我这边并没有复现，可以 gdb attach 上去，看下卡在哪一行
