### ISSUE TITLE
Do you have plan to support ANE or MPS backend from apple?

### ISSUE THREAD

**Issue by adonishong** [li-plus/chatglm.cpp#60]
Sincerely appreciate for your work, do you guys have any plan to support ANE or MPS backend from apple?

**Comment by li-plus** [comment]
Thanks. I'm working to support Metal backend on Apple M2 these days.

**Comment by adonishong** [comment]
> Thanks. I'm working to support Metal backend on Apple M2 these days.

Just noticed the existence of metal branch, looking forward to your update. ^_^

**Comment by adonishong** [comment]
Till 07/26/23

MPS backend from M2 Max is perfect, fantastic work, thank you ^_^

1. git clone
2. git check out metal
3. git submodule update --init --recursive
4. cmake -B build -DGGML_METAL=ON && cmake --build build -j
5. ./build/bin/main -m ./examples/chatglm2-ggml.bin
everything is perfect till this part, fantastic work !!! ^_^
6. CMAKE_ARGS="-DGGML_METAL=ON" pip install .
7. cd examples
8. python ./cli_chat.py -m ./chatglm2-ggml.bin
get this error:
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '(null)'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."

**Comment by li-plus** [comment]
Thanks for your info. I've fixed the missing `ggml-metal.metal` during python package installation. The metal branch is now merged into the main branch. You may try upgrading your python package by `CMAKE_ARGS="-DGGML_METAL=ON" pip3 install -U chatglm-cpp -v --force-reinstall --no-cache-dir` and the metal backend should work fine. Feel free to re-open this issue if you run into any problem.

**Comment by adonishong** [comment]
Just tried the latest version, metal works perfect now. Thanks for your excellent repo. ^_^
