### ISSUE TITLE
num_threads的含义是什么

### ISSUE THREAD

**Issue by wqh17101** [li-plus/chatglm.cpp#62]
chatglm2本身并没有这个参数，num_threads

**Comment by li-plus** [comment]
推理使用的cpu线程数量，一般用默认值就可以

**Comment by wqh17101** [comment]
我看默认是0？

**Comment by li-plus** [comment]
0就会自动选择线程数：
* 如果用cpu推理，默认等于物理核数
* 如果用gpu或开启cpu blas，默认为1
