### ISSUE TITLE
Adding profiling info for chatglm.cpp

### ISSUE THREAD

**Issue by sammysun0711** [li-plus/chatglm.cpp#8]
Hi, 
First of all, thanks for creating interesting project for ChatGLM.
I wonder if you plan to add performance profiling information similar to [llama_print_timings](https://github.com/ggerganov/llama.cpp/blob/b8c8dda75fdf5fdea49c80af36818e7c30fe0ddf/llama.cpp#L3432C6-L3432C25) in llama.cpp

**Comment by li-plus** [comment]
It's in schedule. Will collect performance results through something like a `PerfStreamer`.
