### ISSUE TITLE
api接口

### ISSUE THREAD

**Issue by Vincent131499** [li-plus/chatglm.cpp#82]
使用python convert.py转换完模型之后，进行了框架编译cmake -B build -DGGML_CUBLAS=ON && cmake --build build -j；
后面打算尝试api接口服务，运行：
CMAKE_ARGS="-DGGML_CUBLAS=ON" pip install chatglm-cpp[api]
但在安装python库给出以下提示信息：
WARNING: chatglm-cpp 0.2.2 does not provide the extra 'api'
不清楚对不对。
随后开启api服务：
MODEL=../chatglm2-6b-ggml-q4_1.bin uvicorn chatglm_cpp.langchain_api:app --host 127.0.0.1 --port 8000
给出以下bug：
File "/workspace/chatglm.cpp-master/chatglm.cpp/chatglm_cpp/__init__.py", line 6, in <module>
    import chatglm_cpp._C as _C
ModuleNotFoundError: No module named 'chatglm_cpp._C'

麻烦看下啊

**Comment by edison0817** [comment]
把chatglm.cpp升级到0.23

**Comment by li-plus** [comment]
带api server的包刚发版到pypi，试试重新安装下 `pip install -U 'chatglm-cpp[api]' --force-reinstall`

**Comment by edison0817** [comment]
li-plus您好，请问windows下，用什么命令启动api服务，pyhton环境已经安装好了chatglm.cpp和chatglm-cpp[api]，用示例的命令会报以下错误。
'MODEL' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by li-plus** [comment]
`MODEL`是一个环境变量，试试这么设置：
```sh
set MODEL=./chatglm2-ggml.bin
uvicorn chatglm_cpp.langchain_api:app --host 127.0.0.1 --port 8000
```

**Comment by edison0817** [comment]
> `MODEL`是一个环境变量，试试这么设置：
> 
> ```shell
> set MODEL=./chatglm2-ggml.bin
> uvicorn chatglm_cpp.langchain_api:app --host 127.0.0.1 --port 8000
> ```
 感谢指导，可以使用了。
